# EmKa Akademi

In [15]:
import pandas as pd
import numpy as np


1. İndexlerinde "Breaking Bad" , "Chernobyl" , "Leyla ile Mecnun" , "X-Men"  , "Captain America"  , "Disaster Movie" olan Datasında 9.4 , 9.3 , 8.8 , 8.4 , 3.8 , 2.1 olan bir seri oluşturun.(2 Farklı yolla da oluşturun) (Datayı ve İndexleri liste olarak göndererek ve doğrudan dictionary göndererek.)

In [16]:
index_list = ["Breaking Bad", "Chernobyl", "Leyla ile Mecnun", "X-Men", "Captain America", "Disaster Movie"]
data_list = [9.4 , 9.3 , 8.8 , 8.4 , 3.8 , 2.1]

In [17]:
# 1. Yol - Liste Göndererek
pd.Series(data=data_list, index=index_list)

Breaking Bad        9.4
Chernobyl           9.3
Leyla ile Mecnun    8.8
X-Men               8.4
Captain America     3.8
Disaster Movie      2.1
dtype: float64

In [18]:
# 1. Yol - Dict Göndererek
pd.Series({"Breaking Bad":9.4,
           "Chernobyl":9.3,
           "Leyla ile Mecnun":8.8,
           "X-Men":8.4,
           "Captain America":3.8,
           "Disaster Movie":2.1})

Breaking Bad        9.4
Chernobyl           9.3
Leyla ile Mecnun    8.8
X-Men               8.4
Captain America     3.8
Disaster Movie      2.1
dtype: float64

2. donem1_mat adında bir seri oluşturun. Bu serinin içinde "Ali" ,"Deniz" ,"Aslı" ,"Burak" ,"Kerem" ,"Yasemin" ,"Derya" index değerleri olsun, 
   85, 80 , 94 , 74 , 91 , 96 , 70 data değerleri olsun. Bu şekilde donem1 adında öğrencilerin 1.dönem matematik nor ortalamalarının tutulduğu bir seri oluşturun.

   donem2_mat adında başka bir seri oluşturun. Okula yeni bir öğrenci gelmiş olsun ve indexlerde bu sefer "Ali" ,"Deniz" ,"Aslı" ,"Burak" ,"Kerem" ,"Yasemin" ,"Derya" ,"Mert"         indexleri olsun. 80, 92 , 85 , 87, 90 , 92, 100, 83 ise dataları olsun. Bu iki seriyi birleştirerek bütün öğrencilerin yıl sonu matematik ORTALAMASINI hesaplayın.

   Not : Eğer bir öğrencinin sadece ikinci dönem notu bulunuyorsa, birinci dönem hesaba eklenmeden ikinci dönem notu yıl sonu notu olarak hesaplansın.

In [19]:
donem1_mat = pd.Series(data=[85, 80, 94, 74, 91, 96, 70], index=["Ali", "Deniz", "Asli", "Burak", "Kerem", "Yasemin", "Derya"])
donem2_mat = pd.Series(data=[80, 92, 85, 87, 90, 92, 100, 83], index=["Ali", "Deniz", "Asli", "Burak", "Kerem", "Yasemin", "Derya", "Mert"])

In [20]:
# donem1_mat serisini oluşturma
donem1_mat

Ali        85
Deniz      80
Asli       94
Burak      74
Kerem      91
Yasemin    96
Derya      70
dtype: int64

In [21]:
# donem2_mat serisini oluşturma
donem2_mat

Ali         80
Deniz       92
Asli        85
Burak       87
Kerem       90
Yasemin     92
Derya      100
Mert        83
dtype: int64

In [22]:
# Dönem sonu ortalamlarını alma
donem_sonu = (donem1_mat+donem2_mat)/2
donem_sonu

Ali        82.5
Asli       89.5
Burak      80.5
Deniz      86.0
Derya      85.0
Kerem      90.5
Mert        NaN
Yasemin    94.0
dtype: float64

In [23]:
# NaN değer doldurma
donem_sonu.fillna(donem2_mat, inplace=True)
donem_sonu

Ali        82.5
Asli       89.5
Burak      80.5
Deniz      86.0
Derya      85.0
Kerem      90.5
Mert       83.0
Yasemin    94.0
dtype: float64

3. İndexlerinde "Osman", "Ozlem", "İnci", "Koray", "Melek" olan, columnlarında "Sınıf" , "Cinsiyet" , "Favori Ders" isimlerinde 3 column bulunan bir DF oluşturacaksınız. Osman'ın sınıfı 8 , cinsiyeti "E" , Favori Dersi "Fen"
Ozlem'in sınıfı 11 , cinsiyeti "K" , Favori Dersi "Mat"
İnci'nin sınıfı 5 , cinsiyeti "K" , Favori Dersi "Sosyal"
Koray'ın sınıfı 9 , cinsiyeti "E" , Favori Dersi "Mat"
Meleğin sınıfı 7 , cinsiyeti "K" , Favori Dersi "Ing"          Olacak şekilde bir df oluşturun.


In [24]:
index_list = ["Osman", "Ozlem", "İnci", "Koray", "Melek"]
column_list = ["Sinif" , "Cinsiyet" , "Favori Ders"]
datas = [[8,"E","Fen"],[11,"K","Mat"],[5,"K","Sosyal"],[9,"E","Mat"],[7,"K","Ing"]]

In [25]:
df = pd.DataFrame(data=datas, columns=column_list, index=index_list)
df

Sinif Cinsiyet Favori Ders
Osman      8        E         Fen
Ozlem     11        K         Mat
İnci       5        K      Sosyal
Koray      9        E         Mat
Melek      7        K         Ing

4. GitHubda bulunan "Advertising.csv" reklam datasını herhangi bir platformda DF olarak okuyun ve "df_adv" adında bir değişkene atayın. Ardından df_adv değişkeninin ilk 3 satırına, son 3 satırına , rastgele 3 satırına bakın.

In [26]:
df_adv = pd.read_csv("Advertising.csv")

In [27]:
df_adv.head(3)

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3

In [28]:
df_adv.tail(3)

TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

5. Elde ettiğiniz "df_adv" infosuna ve describe'ına bakın ve yorumlamaya çalışın.

In [29]:
df_adv.info()
# Toplam 200 entry varmış indexleri 0 dan 199 a kadar NaN değer yok ve hepsi float veri tipinde.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [31]:
df_adv.describe().T

count      mean        std  min     25%     50%      75%    max
TV         200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
radio      200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
newspaper  200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0
sales      200.0   14.0225   5.217457  1.6  10.375   12.90   17.400   27.0

6. df_adv içinden sadece "TV" sütununu seri olarak çekin.

In [32]:
df_adv["TV"]

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

7. df_adv içinden "TV" ve "sales" sütununu çekin ve df_salesTV adında bir değişkene atayın.

In [36]:
df_salesTV = df_adv[["TV","sales"]]
df_salesTV.head()

TV  sales
0  230.1   22.1
1   44.5   10.4
2   17.2    9.3
3  151.5   18.5
4  180.8   12.9

8. df_adv içindeki "TV" , "radio" , "newspaper" sütunlarındaki değerleri toplayarak "total_adv" adında yeni bir sütun oluşturun.

In [43]:
df_adv["total_dv"] = df_adv["TV"]+df_adv["radio"]+df_adv["newspaper"]
df_adv.head()

TV  radio  newspaper  sales  total_dv
0  230.1   37.8       69.2   22.1     337.1
1   44.5   39.3       45.1   10.4     128.9
2   17.2   45.9       69.3    9.3     132.4
3  151.5   41.3       58.5   18.5     251.3
4  180.8   10.8       58.4   12.9     250.0

9. df_adv içindeki "sales" sütununun drop edilmiş halini ekrana yazdırın. (Kalıcı hale getirmeyin. Sadece ekrana bastırın)

In [45]:
df_adv.drop("sales", axis=1)

TV  radio  newspaper  total_dv
0    230.1   37.8       69.2     337.1
1     44.5   39.3       45.1     128.9
2     17.2   45.9       69.3     132.4
3    151.5   41.3       58.5     251.3
4    180.8   10.8       58.4     250.0
..     ...    ...        ...       ...
195   38.2    3.7       13.8      55.7
196   94.2    4.9        8.1     107.2
197  177.0    9.3        6.4     192.7
198  283.6   42.0       66.2     391.8
199  232.1    8.6        8.7     249.4

[200 rows x 4 columns]

10. df_adv içindeki son 50 index'i(satırı) çekin ve ekrana yazdırın.

In [46]:
df_adv.tail(50)

TV  radio  newspaper  sales  total_dv
150  280.7   13.9       37.0   16.1     331.6
151  121.0    8.4       48.7   11.6     178.1
152  197.6   23.3       14.2   16.6     235.1
153  171.3   39.7       37.7   19.0     248.7
154  187.8   21.1        9.5   15.6     218.4
155    4.1   11.6        5.7    3.2      21.4
156   93.9   43.5       50.5   15.3     187.9
157  149.8    1.3       24.3   10.1     175.4
158   11.7   36.9       45.2    7.3      93.8
159  131.7   18.4       34.6   12.9     184.7
160  172.5   18.1       30.7   14.4     221.3
161   85.7   35.8       49.3   13.3     170.8
162  188.4   18.1       25.6   14.9     232.1
163  163.5   36.8        7.4   18.0     207.7
164  117.2   14.7        5.4   11.9     137.3
165  234.5    3.4       84.8   11.9     322.7
166   17.9   37.6       21.6    8.0      77.1
167  206.8    5.2       19.4   12.2     231.4
168  215.4   23.6       57.6   17.1     296.6
169  284.3   10.6        6.4   15.0     301.3
170   50.0   11.6       18.4    8.4      80.0
171  164.5   20.9       47.4   14.5     232.8
172   19.6   20.1       17.0    7.6      56.7
173  168.4    7.1       12.8   11.7     188.3
174  222.4    3.4       13.1   11.5     238.9
175  276.9   48.9       41.8   27.0     367.6
176  248.4   30.2       20.3   20.2     298.9
177  170.2    7.8       35.2   11.7     213.2
178  276.7    2.3       23.7   11.8     302.7
179  165.6   10.0       17.6   12.6     193.2
180  156.6    2.6        8.3   10.5     167.5
181  218.5    5.4       27.4   12.2     251.3
182   56.2    5.7       29.7    8.7      91.6
183  287.6   43.0       71.8   26.2     402.4
184  253.8   21.3       30.0   17.6     305.1
185  205.0   45.1       19.6   22.6     269.7
186  139.5    2.1       26.6   10.3     168.2
187  191.1   28.7       18.2   17.3     238.0
188  286.0   13.9        3.7   15.9     303.6
189   18.7   12.1       23.4    6.7      54.2
190   39.5   41.1        5.8   10.8      86.4
191   75.5   10.8        6.0    9.9      92.3
192   17.2    4.1       31.6    5.9      52.9
193  166.8   42.0        3.6   19.6     212.4
194  149.7   35.6        6.0   17.3     191.3
195   38.2    3.7       13.8    7.6      55.7
196   94.2    4.9        8.1    9.7     107.2
197  177.0    9.3        6.4   12.8     192.7
198  283.6   42.0       66.2   25.5     391.8
199  232.1    8.6        8.7   13.4     249.4

11. df_adv içinde satışları 25'den fazla olanları getirin.

In [47]:
df_adv[df_adv["sales"]>25]

TV  radio  newspaper  sales  total_dv
36   266.9   43.8        5.0   25.4     315.7
98   289.7   42.3       51.2   25.4     383.2
147  243.2   49.0       44.3   25.4     336.5
175  276.9   48.9       41.8   27.0     367.6
183  287.6   43.0       71.8   26.2     402.4
198  283.6   42.0       66.2   25.5     391.8

12. df_adv içinde "TV" reklamlarına 250'den fazla ve "newspaper" reklamlarına 60'dan fazla harcama yapanları getirin.

In [48]:
df_adv[(df_adv["TV"]>250)&(df_adv["newspaper"]>60)]

TV  radio  newspaper  sales  total_dv
93   250.9   36.5       72.3   22.2     359.7
101  296.4   36.3      100.9   23.8     433.6
183  287.6   43.0       71.8   26.2     402.4
198  283.6   42.0       66.2   25.5     391.8

13. df_adv içinde "newspaper" reklam harcamaları 70'den fazla VEYA "radio" reklam harcamaları 50'den fazla olanları getirin.

In [49]:
df_adv[(df_adv["radio"]<50) | (df_adv["newspaper"]>70)]

TV  radio  newspaper  sales  total_dv
0    230.1   37.8       69.2   22.1     337.1
1     44.5   39.3       45.1   10.4     128.9
2     17.2   45.9       69.3    9.3     132.4
3    151.5   41.3       58.5   18.5     251.3
4    180.8   10.8       58.4   12.9     250.0
..     ...    ...        ...    ...       ...
195   38.2    3.7       13.8    7.6      55.7
196   94.2    4.9        8.1    9.7     107.2
197  177.0    9.3        6.4   12.8     192.7
198  283.6   42.0       66.2   25.5     391.8
199  232.1    8.6        8.7   13.4     249.4

[200 rows x 5 columns]

14. df_adv içinde "sales" ları 10 ile 15(10 ve 15 dahil) arasında olanları getirin.

In [50]:
df_adv[df_adv["sales"].between(10, 15)]

TV  radio  newspaper  sales  total_dv
1     44.5   39.3       45.1   10.4     128.9
4    180.8   10.8       58.4   12.9     250.0
6     57.5   32.8       23.5   11.8     113.8
7    120.2   19.6       11.6   13.2     151.4
9    199.8    2.6       21.2   10.6     223.6
..     ...    ...        ...    ...       ...
181  218.5    5.4       27.4   12.2     251.3
186  139.5    2.1       26.6   10.3     168.2
190   39.5   41.1        5.8   10.8      86.4
197  177.0    9.3        6.4   12.8     192.7
199  232.1    8.6        8.7   13.4     249.4

[80 rows x 5 columns]

15. df_adv içinde "sales" ları tam olarak 18.3 veya 14.0 veya 25.5 veya 21.7 veya 13.6 veya 6.9 olanları getirin.

In [52]:
# isin() fonksiyonuyla beraber çoklu değer kontrolü yapabiliriz.
desired_values = [18.3, 14.0, 25.5, 21.7, 13.6, 6.9]
df_adv[df_adv["sales"].isin(desired_values)]

TV  radio  newspaper  sales  total_dv
63   102.7   29.6        8.4   14.0     140.7
70   199.1   30.6       38.7   18.3     268.4
76    27.5    1.6       20.7    6.9      49.8
83    68.4   44.5       35.6   13.6     148.5
84   213.5   43.0       33.8   21.7     290.3
198  283.6   42.0       66.2   25.5     391.8

16. GitHubda bulunan "tips.csv" restoran datasını "df_tips" adıyla okuyun. Ardından ilk 5 satırına bakın.

In [53]:
df_tips = pd.read_csv("tips.csv")

In [54]:
df_tips.head()

total_bill   tip     sex smoker  day    time  size  price_per_person   
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49  \
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

17. df_tips'in "CC Number" ve "Payment ID" column'larını kalıcı olarak düşürün.

In [77]:
df_tips.drop(["CC Number", "Payment ID"], axis=1, inplace=True)
df_tips.head()

total_bill   tip     sex smoker  day    time  size  price_per_person   
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49  \
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name  
0  Christy Cunningham  
1      Douglas Tucker  
2      Travis Walters  
3    Nathaniel Harris  
4        Tonya Carter

18. df_tips'in "Payer Name" column'unu kalıcı olarak index yapın ve artık columndan düşürün.

In [80]:
df_tips = df_tips.set_index("Payer Name", drop=True)
df_tips.head()

total_bill   tip     sex smoker  day    time  size   
Payer Name                                                               
Christy Cunningham       16.99  1.01  Female     No  Sun  Dinner     2  \
Douglas Tucker           10.34  1.66    Male     No  Sun  Dinner     3   
Travis Walters           21.01  3.50    Male     No  Sun  Dinner     3   
Nathaniel Harris         23.68  3.31    Male     No  Sun  Dinner     2   
Tonya Carter             24.59  3.61  Female     No  Sun  Dinner     4   

                    price_per_person  
Payer Name                            
Christy Cunningham              8.49  
Douglas Tucker                  3.45  
Travis Walters                  7.00  
Nathaniel Harris               11.84  
Tonya Carter                    6.15

19. df_tips içindeki kayıtlardan kişi sayısı 4 veya 4'den fazla olan siparişlerin kaç tane olduğunu bulun.(Sorguyu yazıp istediğimiz satırları getirdikten sonra basitçe len() fonksiyonunu kullanarak sayılarını bulabilirsiniz. Veya daha güzeli .shape[0] yaparak elde ettiğiniz sorguda kaç satır olduğunun sayısına ulaşabilirsiniz.)

In [82]:
df_tips[df_tips["size"]>=4].shape[0]

46

20. df_tips içindeki Kişi sayısı 2 ya da 3 olan, sigara içen, erkek olan ve ödediği ücret 20 dolardan az olan kişi sayısını bulalım.

In [85]:
df_tips[(df_tips["size"].between(2,3))&(df_tips["smoker"]=="Yes")&(df_tips["total_bill"]<20)].shape[0]

49